// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  apiSidebar: [{ type: "autogenerated", dirName: "api" }],
  learnSidebar: [{ type: "autogenerated", dirName: "learn" }],
};

module.exports = sidebars;
