name: Publish to npm registry

on:
  push:
    branches:
      - main
      - beta
      - alpha
      - development
      - 1-initialize-repository
  pull_request:
    branches:
      - main
      - beta
      - alpha
      - development

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      VERSION: ${{ steps.publish.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Verify integrity
        run: npm audit signatures
      - name: Build package
        run: npm run build
      - name: Publish package
        id: publish
        run: npx semantic-release

  update-docs:
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: Echo version
        run: echo ${{ needs.publish.outputs.VERSION }}
