name: Publish to npm registry

on:
  push:
    branches:
      - main
      - beta
      - alpha
      - development

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: deployment
    outputs:
      VERSION: ${{ steps.publish.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Verify integrity
        run: npm audit signatures
      - name: Build package
        run: npm run build
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Publish package
        id: publish
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_NAME: ${{ steps.import_gpg.outputs.name }}
          GIT_AUTHOR_EMAIL: ${{ steps.import_gpg.outputs.email }}
          GIT_COMMITTER_NAME: ${{ steps.import_gpg.outputs.name }}
          GIT_COMMITTER_EMAIL: ${{ steps.import_gpg.outputs.email }}

  update-docs:
    needs: publish
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository on source branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          path: src
      - name: Checkout repository on documentation branch
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          path: docs
          ref: gh-pages
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: docs/package-lock.json
      - name: Install dependencies
        run: npm ci
        working-directory: docs
      - name: Verify integrity
        run: npm audit signatures
        working-directory: docs
      - name: Clean API documentation
        run: rm -rf docs/api
        working-directory: docs
      - name: Build documentation
        run: TYPEDOC_TSCONFIG="../src/tsconfig.build.json" TYPEDOC_ENTRY_POINT="../src/src/main/ts" npm run docusaurus generate-typedoc
        working-directory: docs
      - name: Build CHANGELOG.md
        run: |
          ls -la ../src
          echo "---" > docs/api/CHANGELOG.md
          echo "id: changelog" >> docs/api/CHANGELOG.md
          echo "title: CHANGELOG" >> docs/api/CHANGELOG.md
          echo "sidebar_label: CHANGELOG" >> docs/api/CHANGELOG.md
          echo "sidebar_position: 2" >> docs/api/CHANGELOG.md
          echo "custom_edit_url: null" >> docs/api/CHANGELOG.md
          echo "---" >> docs/api/CHANGELOG.md
          echo "" >> docs/api/CHANGELOG.md
          cat ../src/CHANGELOG.md >> docs/api/CHANGELOG.md
        working-directory: docs
      - name: Tag documentation
        run: npm run docusaurus docs:version ${{ needs.publish.outputs.VERSION }}
        working-directory: docs
      - name: Prettify all new files
        run: |
          npx prettier --write docs/api
          npx prettier --write versions.json
          npx prettier --write versioned_docs/version-${{ needs.publish.outputs.VERSION }}
          npx prettier --write versioned_sidebars/version-${{ needs.publish.outputs.VERSION }}-sidebars.json
        working-directory: docs
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          workdir: docs
      - name: Commit documentation
        run: |
          git remote set-url origin https://${{ secrets.SERVICE_ACCOUNT_TOKEN }}@github.com/${{ github.repository }}.git/
          git add versions.json
          git add versioned_docs/version-${{ needs.publish.outputs.VERSION }}
          git add versioned_sidebars/version-${{ needs.publish.outputs.VERSION }}-sidebars.json
          git commit -m "docs(api): update for version ${{ needs.publish.outputs.VERSION }}"
          git push
        working-directory: docs
