name: Action tests

on:
  pull_request:
    branches:
      - development
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print directory
        run: pwd

      - name: List files
        run: ls -la

      - name: Test os
        if: runner.os != 'ubuntu-latest'
        run: echo "Not ubuntu"
      - name: Test os positive
        if: runner.os == 'ubuntu-latest'
        run: echo "Ubuntu"

      - name: Echo branch name
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.event.pull_request.base.ref }}
