name: Validate code with tests and static analysis

on:
  pull_request:
    branches:
      - main
      - beta
      - alpha

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Check formatting errors
        run: npx prettier --check .

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Check linting errors
        run: npx eslint .

  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test:coverage

  # analyze:
  # runs-on: ubuntu-latest
  # timeout-minutes: 360
  # needs:
  #   - build
  # permissions:
  #   actions: read
  #   contents: read
  #   security-events: write

  # strategy:
  #   fail-fast: false
  #   matrix:
  #     language:
  #       - javascript-typescript

  # steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4
  #   - name: Initialize CodeQL
  #     uses: github/codeql-action/init@v2
  #     with:
  #       languages: ${{ matrix.language }}
  #   - name: Perform CodeQL Analysis
  #     uses: github/codeql-action/analyze@v2
  #     with:
  #       category: /language:${{matrix.language}}
